# https://github.com/czl9707/gh-space-shooter
name: Update Space Shooter Game

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Space Shooter GIF Generator
        uses: YiweiShen/gh-space-shooter@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: 'game.gif'
          strategy: 'random'

      - name: Commit  GIF
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add game.gif
          git commit -m "Update space shooter GIF" || exit 0
          git push
